name: "Prepare FORGE minimal ubuntu image"
description: "Install minimal Python dependencies required for FORGE repository operations"

runs:
  using: "composite" # <-- this is the important part
  steps:
  - name: Install dependencies
    shell: bash
    run: |
      python3 -m pip install pyyaml jsonpath_ng
